# 单智能体配置文件

# 智能体配置
agent_config:
  agent_class: "modes.single_agent.llm_agent.LLMAgent"
  max_failures: 3
  max_history: 20

  # 环境描述配置
  environment_description:
    # 详细程度: 'full' (完整环境) / 'room' (当前房间) / 'brief' (仅智能体状态)
    detail_level: 'full'
    # 是否显示物体属性
    show_object_properties: true
    # 是否只显示已发现的内容 全局观察 or 部分观察
    only_show_discovered: true
    # 是否包含其他智能体信息
    include_other_agents: true
    # 更新频率 (0=每步更新, >0=按频率更新)
    update_frequency: 0

# 任务执行设置
execution:
  max_total_steps: 400  # 最大总执行步数
  max_steps_per_task: 20  # 每个任务的最大步数

# 评测模式设置
evaluation:
  # 评测类型: 'sequential' (逐个评测) 或 'combined' (混合评测) 或 'independent' (独立评测)
  task_type: 'independent'

  # 默认场景设置
  default_scenario: '00002'

  # 运行设置
  run_settings:
    # 默认运行后缀
    default_suffix: 'demo'
    # 日志级别: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
    log_level: 'INFO'

  # 输出设置
  output:
    # 输出目录
    base_dir: 'output'
    # 是否保存轨迹文件
    save_trajectory: true
    # 是否保存紧凑轨迹文件
    save_compact_trajectory: true
    # 是否生成评测报告
    generate_report: true

  # 任务执行配置
  execution:
    # 任务超时时间（秒）- 注意：当前未实现超时机制
    timeout_seconds: 900



# 并行评测配置
parallel_evaluation:
  # 是否启用并行评测
  enabled: true

  # 场景级并行配置
  scenario_parallelism:
    # 最大并行场景数
    max_parallel_scenarios: 3

  # 场景选择配置
  # 说明：首先根据场景选择配置确定基础场景列表，然后应用任务筛选
  scenario_selection:
    # 场景选择模式
    # 选项:
    #   - 'all': 选择所有可用场景
    #   - 'range': 选择指定范围内的场景 (如 00001-00010)
    #   - 'list': 选择指定列表中的场景
    mode: 'range'

    # 范围模式配置 (当mode='range'时使用)
    range:
      start: '00001'  # 起始场景ID (5位数字，如 00001)
      end: '00005'    # 结束场景ID (5位数字，如 00010)

    # 列表模式配置 (当mode='list'时使用)
    # 用法：取消注释并指定场景ID列表
    # list: ['00001', '00003', '00005']

    # 任务筛选配置 (与场景选择取交集)
    # 说明：任务筛选用于根据任务特征进一步筛选要评测的场景
    # 只有包含符合筛选条件任务的场景才会被评测
    task_filter:
      # 任务类别筛选 (可选)
      # 说明：根据任务的task_category字段筛选任务
      # 支持的类别:
      #   - 'direct_command': 直接命令任务 (如"将苹果放到桌子上")
      #   - 'attribute_reasoning': 属性推理任务 (如"找到最重的物体")
      #   - 'tool_use': 工具使用任务 (如"用锤子修理设备")
      #   - 'spatial_reasoning': 空间推理任务 (如"将物体放到最近的容器中")
      #   - 'compound_reasoning': 复合推理任务
      #   - 'explicit_collaboration': 显式协作任务 (明确指定多智能体协作)
      #   - 'implicit_collaboration': 隐式协作任务 (需要智能体自主协作)
      #   - 'compound_collaboration': 复合协作任务
      # 用法：取消注释并指定要筛选的类别列表
      # categories: ['direct_command', 'attribute_reasoning']
      #
      # 示例配置（已启用）：只评测直接命令任务
        categories: ['tool_use']



