# 单智能体配置文件

# 智能体配置
agent_config:
  agent_class: "modes.single_agent.llm_agent.LLMAgent"
  max_failures: 3
  max_history: 20

  # 环境描述配置
  environment_description:
    # 详细程度: 'full' (完整环境) / 'room' (当前房间) / 'brief' (仅智能体状态)
    detail_level: 'full'
    # 是否显示物体属性
    show_object_properties: true
    # 是否只显示已发现的内容 全局观察 or 部分观察
    only_show_discovered: true
    # 是否包含其他智能体信息
    include_other_agents: true
    # 更新频率 (0=每步更新, >0=按频率更新)
    update_frequency: 0

# 任务执行设置
execution:
  max_total_steps: 400  # 最大总执行步数
  max_steps_per_task: 20  # 每个任务的最大步数

# 评测模式设置
evaluation:
  # 评测类型: 'sequential' (逐个评测) 或 'combined' (混合评测) 或 'independent' (独立评测)
  task_type: 'independent'

  # 默认场景设置
  default_scenario: '00002'

  # 运行设置
  run_settings:
    # 默认运行后缀
    default_suffix: 'demo'
    # 日志级别: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
    log_level: 'INFO'

  # 输出设置
  output:
    # 输出目录
    base_dir: 'output'
    # 是否保存轨迹文件
    save_trajectory: true
    # 是否保存紧凑轨迹文件
    save_compact_trajectory: true
    # 是否生成评测报告
    generate_report: true

  # 任务执行配置
  execution:
    # 任务超时时间（秒）
    timeout_seconds: 900

    # 逐个评测模式配置
    sequential:
      # 是否在子任务失败时继续执行下一个任务
      continue_on_failure: true
      # 是否在每个子任务开始前清空历史记录
      clear_history_between_tasks: true
      # 子任务间的延迟时间（秒）
      delay_between_tasks: 1.0
      # 是否显示子任务进度
      show_task_progress: true

    # 混合评测模式配置
    combined:
      # 任务描述之间的分隔符
      task_separator: "\n\n下一个任务：\n"
      # 是否在任务描述前添加序号
      add_task_numbers: true
      # 是否显示任务分隔信息
      show_task_separator: true

    # Independent evaluation mode configuration
    independent:
      # Whether to continue executing next task when subtask fails
      continue_on_failure: true

      # Delay time between subtasks (seconds) - for resource cleanup
      delay_between_subtasks: 1.0

      # Whether to show subtask execution progress
      show_subtask_progress: true

      # Output management configuration
      output_management:
        # Subtask output directory naming pattern
        subtask_dir_pattern: 'subtask_{index:03d}_{hash}'

        # Whether to create independent directories for subtasks (set to false to avoid directory redundancy)
        create_subtask_directories: false

        # Whether to save detailed logs for each subtask
        save_individual_logs: true

        # Whether to generate subtask-level trajectory files
        generate_subtask_trajectories: true

      # Result analysis configuration
      analysis:
        # Whether to perform performance comparison between subtasks
        compare_subtask_performance: true

        # Whether to analyze success rate by task category
        analyze_category_success_rate: true

        # Whether to generate execution time distribution charts
        generate_timing_analysis: false



# 并行评测配置
parallel_evaluation:
  # 是否启用并行评测
  enabled: true

  # 场景级并行配置
  scenario_parallelism:
    # 最大并行场景数
    max_parallel_scenarios: 3

  # 场景选择配置
  scenario_selection:
    # 场景选择模式: 'all' (所有场景), 'range' (范围), 'list' (指定列表)
    mode: 'range'

    # 范围模式配置 (mode='range'时使用)
    range:
      start: '00001'  # 起始场景ID
      end: '00005'    # 结束场景ID (测试并发功能，评测5个场景)

    # 列表模式配置 (mode='list'时使用)
    # list: ['00001', '00003', '00005']

  # 输出配置
  output:
    # 是否保存各场景的详细轨迹
    save_individual_trajectories: true
    # 是否生成汇总报告
    generate_summary_report: true

