# 默认智能体配置

# 智能体类型设置
agent_type: llm  # 可选值: llm, rule_based, hybrid

# LLM智能体设置
llm_agent:
  # 使用的LLM配置
  llm_config: llm_config
  # 最大尝试次数
  max_attempts: 3
  # 思考链 (Chain of Thought) 设置
  use_cot: true
  # 动作验证
  validate_actions: true

# 日志设置
logging:
  enabled: true
  level: info  # 可选: debug, info, warning, error
  log_file: "agent.log"
  log_to_console: true

# 历史记录设置
history:
  save_history: true
  max_history_length: 50
  history_file: "agent_history.json"