# Centralized dual-agent configuration

# Coordinator settings
coordinator:
  # LLM configuration to use
  llm_config: llm_config
  # Maximum history length
  max_chat_history: -1  # -1 means no limit on history record count

# Worker agent settings
worker_agents:
  # LLM configuration to use
  llm_config: llm_config
  # Maximum history length
  max_chat_history: -1  # -1 means no limit on history record count

# Task execution settings
execution:
  max_total_steps: 300  # Maximum total execution steps

# Task evaluator settings
task_evaluator:
  max_steps_per_task: 30  # Maximum steps per subtask

# Evaluation mode settings
evaluation:
  # Evaluation type: 'sequential' (sequential evaluation) or 'combined' (combined evaluation) or 'independent' (independent evaluation)
  task_type: 'sequential'

  # Default scenario settings
  default_scenario: '00001'

  # Run settings
  run_settings:
    # Default run suffix
    default_suffix: 'demo'
    # Log level: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
    log_level: 'INFO'

  # Task execution configuration
  execution:
    # Task timeout (seconds)
    timeout_seconds: 900

    # Sequential evaluation mode configuration
    sequential:
      # Whether to continue executing next task when subtask fails
      continue_on_failure: true

    # Combined evaluation mode configuration
    combined:
      # Separator between task descriptions
      task_separator: "\n\nNext task:\n"
      # Whether to add task numbers before task descriptions
      add_task_numbers: true

    # Independent evaluation mode configuration
    independent:
      # Whether to continue executing next task when subtask fails
      continue_on_failure: true

      # Delay time between subtasks (seconds) - for resource cleanup
      delay_between_subtasks: 1.0

      # Whether to show subtask execution progress
      show_subtask_progress: true

      # Output management configuration
      output_management:
        # Subtask output directory naming pattern
        subtask_dir_pattern: 'subtask_{index:03d}_{hash}'

        # Whether to save detailed logs for each subtask
        save_individual_logs: true

        # Whether to generate subtask-level trajectory files
        generate_subtask_trajectories: true



# 并行评测配置
parallel_evaluation:
  # 是否启用并行评测
  enabled: false

  # 场景级并行配置
  scenario_parallelism:
    # 最大并行场景数
    max_parallel_scenarios: 4

  # 场景选择配置
  scenario_selection:
    # 场景选择模式: 'all' (所有场景), 'range' (范围), 'list' (指定列表)
    mode: 'range'

    # 范围模式配置 (mode='range'时使用)
    range:
      start: '00001'  # 起始场景ID
      end: '00010'    # 结束场景ID

    # 列表模式配置 (mode='list'时使用)
    # list: ['00001', '00003', '00005']

  # 输出配置
  output:
    # 是否保存各场景的详细轨迹
    save_individual_trajectories: true
    # 是否生成汇总报告
    generate_summary_report: true
    # 暂停时间（秒）
    pause_duration: 1.0