# 中心化多智能体配置

# 协调器设置
coordinator:
  # 使用的LLM配置
  llm_config: llm_config
  # 最大历史长度
  max_chat_history: 10
  # 环境描述设置
  env_description:
    # 详细程度: full(完整环境), room(当前房间), brief(简要描述)
    detail_level: full
    # 是否显示物体属性
    show_object_properties: true
    # 是否只显示已发现的内容
    only_show_discovered: false

# 工作智能体设置
worker_agents:
  # 默认行为
  default_behavior: "wait_for_instruction"  # 可选: wait_for_instruction, explore, random
  # 环境描述设置
  env_description:
    # 详细程度: full(完整环境), room(当前房间), brief(简要描述)
    detail_level: room
    # 是否显示物体属性
    show_object_properties: false
    # 是否只显示已发现的内容
    only_show_discovered: true

# 协作模式
collaboration:
  # 协作模式
  mode: "hierarchical"  # 可选: hierarchical, cooperative

# 日志设置
logging:
  level: info  # 可选: debug, info, warning, error