# 去中心化多智能体配置

# 自主智能体通用设置
autonomous_agent:
  # 使用的LLM配置
  llm_config: llm_config
  # 最大历史长度
  max_chat_history: 10

# 智能体个性化设置 - 参考CoELA的Alice/Bob设计
agent_personalities:
  # 探索者 - Alice
  explorer:
    personality: "好奇、冒险、细心、主动沟通"
    skills: ["探索", "发现", "记忆地图", "信息收集"]
    communication_preference: "详细描述"
    collaboration_style: "主导型"

  # 操作者 - Bob
  operator:
    personality: "谨慎、精确、专注、善于执行"
    skills: ["操作物体", "精细动作", "解决难题", "任务执行"]
    communication_preference: "简洁高效"
    collaboration_style: "配合型"

# 通信系统设置
communication:
  # 消息队列设置
  message_queue:
    max_size: 100
    timeout_seconds: 30

  # 广播设置
  broadcast:
    enabled: true
    max_recipients: 10

  # 消息类型
  message_types:
    - "info_sharing"      # 信息分享
    - "task_coordination" # 任务协调
    - "help_request"      # 求助请求
    - "status_update"     # 状态更新
    - "strategy_discussion" # 策略讨论

# 任务执行设置
execution:
  max_total_steps: 300  # 最大总执行步数

# 任务评测器设置
task_evaluator:
  max_steps_per_task: 30  # 每个子任务的最大步数

# 评测模式设置
evaluation:
  # 评测类型: 'sequential' (逐个评测) 或 'combined' (混合评测) 或 'independent' (独立评测)
  task_type: 'sequential'

  # 默认场景设置
  default_scenario: '00001'

  # 运行设置
  run_settings:
    # 默认运行后缀
    default_suffix: 'demo'
    # 日志级别: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
    log_level: 'INFO'

  # 任务执行配置
  execution:
    # 任务超时时间（秒）
    timeout_seconds: 900

    # 逐个评测模式配置
    sequential:
      # 是否在子任务失败时继续执行下一个任务
      continue_on_failure: true

    # 混合评测模式配置
    combined:
      # 任务描述之间的分隔符
      task_separator: "\n\n下一个任务：\n"
      # 是否在任务描述前添加序号
      add_task_numbers: true

    # 独立评测模式配置
    independent:
      # 是否在子任务失败时继续执行下一个任务
      continue_on_failure: true

      # 子任务间延迟时间（秒）- 用于资源清理
      delay_between_subtasks: 1.0

      # 是否显示子任务执行进度
      show_subtask_progress: true

      # 输出管理配置
      output_management:
        # 子任务输出目录命名模式
        subtask_dir_pattern: 'subtask_{index:03d}_{hash}'

        # 是否保存每个子任务的详细日志
        save_individual_logs: true

        # 是否生成子任务级别的轨迹文件
        generate_subtask_trajectories: true



# 并行评测配置
parallel_evaluation:
  # 是否启用并行评测
  enabled: false

  # 场景级并行配置
  scenario_parallelism:
    # 最大并行场景数
    max_parallel_scenarios: 4

  # 场景选择配置
  scenario_selection:
    # 场景选择模式: 'all' (所有场景), 'range' (范围), 'list' (指定列表)
    mode: 'range'

    # 范围模式配置 (mode='range'时使用)
    range:
      start: '00001'  # 起始场景ID
      end: '00010'    # 结束场景ID

    # 列表模式配置 (mode='list'时使用)
    # list: ['00001', '00003', '00005']

  # 输出配置
  output:
    # 是否保存各场景的详细轨迹
    save_individual_trajectories: true
    # 是否生成汇总报告
    generate_summary_report: true

  # 结果统计和输出配置
  output:
    # 是否保存详细的执行轨迹
    save_trajectory: true
    # 是否保存详细日志
    save_detailed_logs: true
    # 输出目录
    output_directory: 'output'
    # 是否生成评测报告
    generate_report: true

  # 调试配置
  debug:
    # 是否启用详细日志
    verbose_logging: true
    # 日志级别: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
    log_level: 'INFO'
    # 是否在每步后暂停（用于调试）
    pause_between_steps: false
    # 暂停时间（秒）
    pause_duration: 1.0