# 去中心化多智能体配置

# 自主智能体通用设置
autonomous_agent:
  # 使用的LLM配置
  llm_config: llm_config
  # 最大历史长度
  max_chat_history: 10
  # 环境描述设置
  env_description:
    # 详细程度: full(完整环境), room(当前房间), brief(简要描述)
    detail_level: room
    # 是否显示物体属性
    show_object_properties: true
    # 是否只显示已发现的内容
    only_show_discovered: true

# 智能体个性化设置
agent_personalities:
  # 探索者
  explorer:
    personality: "好奇、冒险、细心"
    skills: ["探索", "发现", "记忆地图"]
    # 探索者的环境描述设置 - 可看到更多细节
    env_description:
      detail_level: room
      show_object_properties: true
      only_show_discovered: false

  # 操作者
  operator:
    personality: "谨慎、精确、专注"
    skills: ["操作物体", "精细动作", "解决难题"]
    # 操作者的环境描述设置 - 更关注物体细节
    env_description:
      detail_level: room
      show_object_properties: true
      only_show_discovered: true

  # 协调者
  coordinator:
    personality: "合作、组织、全局思考"
    skills: ["规划", "协调", "沟通"]
    # 协调者的环境描述设置 - 可看到更多全局信息
    env_description:
      detail_level: full
      show_object_properties: false
      only_show_discovered: false

# 协作模式
collaboration:
  # 是否形成动态团队
  form_dynamic_teams: true

# 日志设置
logging:
  level: info  # 可选: debug, info, warning, error