# OmniEmbodied 主配置文件
# 统一管理整个项目的配置

# 项目基本信息
project:
  name: "OmniEmbodied"
  version: "1.0.0"
  description: "全能具身智能框架"

# 路径配置
paths:
  # 数据目录
  data_root: "data"
  scene_data: "data/scene"
  task_data: "data/task"
  generated_data: "data/generated"
  
  # 输出目录
  output_root: "output"
  logs: "output/logs"
  results: "output/results"
  trajectories: "output/trajectories"
  
  # 配置目录
  config_root: "config"
  config_defaults: "config/defaults"

# 模块配置
modules:
  # 核心框架
  core:
    enabled: true
    config_file: "single_agent_config.yaml"
  
  # 模拟器
  simulator:
    enabled: true
    config_file: "simulator_config.yaml"
    
  # 数据生成
  data_generation:
    enabled: true
    config_files:
      - "pipeline.yaml"
      - "scene_gen_config.yaml"
      - "task_gen_config.yaml"
      - "clue_gen_config.yaml"
  
  # LLM集成
  llm:
    enabled: true
    config_file: "llm_config.yaml"
  
  # 不同执行模式
  modes:
    single_agent:
      enabled: true
      config_file: "single_agent_config.yaml"
    centralized:
      enabled: true
      config_file: "centralized_config.yaml"
    decentralized:
      enabled: true
      config_file: "decentralized_config.yaml"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_handler:
    enabled: true
    filename: "output/logs/omni_embodied.log"
    max_bytes: 10485760  # 10MB
    backup_count: 5
  console_handler:
    enabled: true

# 默认设置
defaults:
  max_steps: 50
  timeout_seconds: 300
  save_trajectories: true
  save_results: true
  enable_visualization: false
