# 单智能体配置文件
# 包含LLM智能体的完整配置参数

# LLM智能体设置
llm_agent:
  # 使用的LLM配置文件名
  llm_config: llm_config
  # 使用的提示词配置文件名
  prompts_config: prompts_config
  # 最大尝试次数
  max_attempts: 3
  # 思考链 (Chain of Thought) 设置
  use_cot: true
  # 动作验证
  validate_actions: true

# 环境描述设置
env_description:
  # 详细程度: full(完整环境), room(当前房间), brief(简要描述)
  detail_level: full
  # 是否显示物体属性
  show_object_properties: true
  # 是否只显示已发现的内容
  only_show_discovered: false
  # 是否包含动态动作描述
  include_dynamic_actions: true

# 历史记录设置
history:
  max_history_length: 500
  max_history_in_prompt: 10  # 控制提示词中显示的历史记录数量

# 任务执行设置
execution:
  max_steps: 50  # 最大执行步数
  step_timeout: 60  # 单步超时时间(秒)