# Test dataset generation configuration file

# Data source configuration
source:
  # Source data directory (relative to project root)
  data_dir: "data/data-all"
  # Task file subdirectory
  task_subdir: "task"
  # Scene file subdirectory  
  scene_subdir: "scene"

# Output configuration
output:
  # Output root directory (relative to project root)
  output_dir: "data/eval/single-independent"
  # Task output subdirectory
  task_subdir: "task"
  # Scene symlink subdirectory
  scene_subdir: "scene"

# Task filtering configuration
task_filter:
  # Agent filtering mode
  # - "single": Generate only single-agent tasks
  # - "multi": Generate only multi-agent tasks  
  # - "all": Generate all tasks
  agent_mode: "single"
  
  # List of task types to generate
  # Single-agent task types: direct_command, attribute_reasoning, tool_use, compound_reasoning
  # Multi-agent task types: explicit_collaboration, implicit_collaboration, compound_collaboration
  task_categories:
    - "direct_command"
    - "attribute_reasoning" 
    - "tool_use"
    - "compound_reasoning"
    # - "explicit_collaboration"
    # - "implicit_collaboration"
    # - "compound_collaboration"
  
  # Target count for each task type
  count_per_category: 200

# Agent selection configuration
agent_selection:
  # Agent selection strategy
  # - "max_weight": Select agent with highest max_weight
  # - "first": Select first agent
  # - "random": Randomly select an agent
  strategy: "max_weight"

# Scene file processing configuration
scene_processing:
  # Whether to create symlinks for scene files
  # true: Create symlinks (Linux/macOS) or symbolic links (Windows)
  # false: Copy and rename scene files
  create_scene_links: true
