# Auto-build documentation and trigger Read the Docs
name: Documentation Build

on:
  push:
    branches: ["main"]
    paths: 
      - "docs/**"
      - "*.py"
      - "**/*.py"
      - ".readthedocs.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "*.py"
      - "**/*.py"
      - ".readthedocs.yaml"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install documentation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Test Sphinx build
      run: |
        cd docs
        make clean
        make html SPHINXOPTS="--keep-going"

    - name: Check for broken links
      run: |
        cd docs
        make linkcheck

    - name: Upload documentation artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/build/html/
        retention-days: 30

    - name: Trigger Read the Docs build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        curl -X POST \
          -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
          "https://readthedocs.org/api/v3/projects/omniembodied/versions/latest/builds/"
      continue-on-error: true

  notify-status:
    runs-on: ubuntu-latest
    needs: build-docs
    if: always()
    steps:
    - name: Notify build status
      run: |
        if [ "${{ needs.build-docs.result }}" == "success" ]; then
          echo "✅ Documentation build completed successfully"
          echo "📖 Documentation will be available at: https://omniembodied.readthedocs.io/"
        else
          echo "❌ Documentation build failed"
          exit 1
        fi 